default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: chat
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: chat
  pool: 5
  timeout: 5000

production:
 adapter: postgresql
 encoding: utf8
 database: chat
 pool: 5
